namespace ArtGallery.Application.DTOs
{
	// -------------------------------------------------------------------
	// DTO class representing the data of a user, used for transferring 
	// user-related information (e.g., when a user logs in or retrieves their profile).
	// This class includes the user's Id, username, email, role, and optionally a token.
	// -------------------------------------------------------------------
	public class UserDto
	{
		// -------------------------------------------------------------------
		// The unique identifier of the user in the system.
		// This ID is typically generated by the database.
		// -------------------------------------------------------------------
		public int Id { get; set; }

		// -------------------------------------------------------------------
		// The username of the user, which is a unique string used for identification.
		// -------------------------------------------------------------------
		public string Username { get; set; } = default!;

		// -------------------------------------------------------------------
		// The email address associated with the user's account.
		// This can be used for authentication and communication purposes.
		// -------------------------------------------------------------------
		public string Email { get; set; } = default!;

		// -------------------------------------------------------------------
		// The role assigned to the user (e.g., "Admin", "Artist", "Buyer").
		// This defines the user's access level and permissions within the system.
		// -------------------------------------------------------------------
		public string Role { get; set; } = default!;

		// -------------------------------------------------------------------
		// Optionally, the authentication token that is returned when the user logs in.
		// This token is used for subsequent API requests to authenticate the user.
		// -------------------------------------------------------------------
		public string? Token { get; set; }
	}
}
